const types = {
    UPDATE_INPUT: 'CALCULATOR_UPDATE_INPUT',
    UPDATE_OUTPUT: 'CALCULATOR_UPDATE_OUTPUT',
    HANDLE_ERROR: 'CALCULATOR_HANDLE_ERROR',
    DELETE_LINE: 'CALCULATOR_DELETE_LINE',
    ADD_LINE: 'CALCULATOR_ADD_LINE',
    REFRESH: 'CALCULATOR_REFRESH'
}

export default types;