const types = {
    UPDATE_INPUT: 'CALCULATOR_UPDATE_INPUT',
    CALCULATE: 'CALCULATOR_CALCULATE',
    HANDLE_ERROR: 'CALCULATOR_HANDLE_ERROR',
    DELETE_ONE: 'CALCULATOR_DELETE_ONE',
    COPY_ONE: 'CALCULATOR_COPY_ONE',
    REFRESH: 'CALCULATOR_REFRESH'
}

export default types;