const types = {
    UPDATE_INPUT: 'CALCULATOR_UPDATE_INPUT',
    UPDATE_OUTPUT: 'CALCULATOR_UPDATE_OUTPUT',
    HANDLE_ERROR: 'CALCULATOR_HANDLE_ERROR',
    SAVE_NOTE: 'CALCULATOR_SAVE_NOTE',
    SAVE_NOTE_ERROR: 'CALCULATOR_SAVE_NOTE_ERROR',
    SAVE_NOTE_SUCCESS: 'CALCULATOR_SAVE_NOTE_SUCCESS',
    FETCH_SAVED: 'CALCULATOR_FETCH_SAVED',
    FETCH_SAVED_ERROR: 'CALCULATOR_FETCH_SAVED_ERROR',
    FETCH_SAVED_SUCCESS: 'CALCULATOR_FETCH_SAVED_SUCCESS',
    REFRESH: 'CALCULATOR_REFRESH',
    SET_EXCHANGE_RATES: 'CALCULATOR_SET_EXCHANGE_RATES',
    SET_VARIABLE: 'CALCULATOR_SET_VARIABLE',
}

export default types;