export const types = {
    LOGIN: 'USER_LOGIN',
    LOGIN_ERROR: 'USER_LOGIN_ERROR',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    LOGOUT: 'USER_LOGOUT',

    SIGNUP: 'USER_SIGNUP',
    SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
    SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',

    EDIT: 'USER_EDIT',
    EDIT_ERROR: 'USER_EDIT_ERROR',
    EDIT_SUCCESS: 'USER_EDIT_SUCCESS',

    SAVE_NOTE: 'CALCULATOR_SAVE_NOTE',
    SAVE_NOTE_ERROR: 'CALCULATOR_SAVE_NOTE_ERROR',
    SAVE_NOTE_SUCCESS: 'CALCULATOR_SAVE_NOTE_SUCCESS',
}

