export const USER = {
    LOGIN: 'USER_LOGIN',
    LOGIN_ERROR: 'USER_LOGIN_ERROR',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    SIGNUP: 'USER_SIGNUP',
    SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
    SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',

    EDIT: 'USER_EDIT',
    EDIT_ERROR: 'USER_EDIT_ERROR',
    EDIT_SUCCESS: 'USER_EDIT_SUCCESS',

    LOGOUT: 'USER_LOGOUT',
}

